"use server";

import { z } from "zod";
import { prisma } from "@/lib/prisma";

const contactSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters"),
  email: z.string().email("Invalid email address"),
  projectType: z.string().min(2, "Please select a project type"),
  message: z.string().min(10, "Message must be at least 10 characters"),
});

export async function submitContact(data: z.infer<typeof contactSchema>) {
  try {
    const validatedData = contactSchema.parse(data);

    // Auto-create the table if it doesn't exist to guarantee it works without prisma db push
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS "Contact" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "email" TEXT NOT NULL,
        "projectType" TEXT NOT NULL,
        "message" TEXT NOT NULL,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Contact_pkey" PRIMARY KEY ("id")
      );
    `);

    // The id is auto-generated by the database default or we can generate it using crypto
    // We'll generate the ID here to satisfy Prisma's schema
    const newId = crypto.randomUUID();

    await prisma.$executeRawUnsafe(`
      INSERT INTO "Contact" ("id", "name", "email", "projectType", "message")
      VALUES ($1, $2, $3, $4, $5)
    `, newId, validatedData.name, validatedData.email, validatedData.projectType, validatedData.message);

    return { success: true };
  } catch (error) {
    console.error("Failed to submit contact:", error);
    return { success: false, error: "Failed to submit request." };
  }
}
